BASE_URL = "https://financialmodelingprep.com/api/v3"

SUPPORTED_CATEGORIES = [
    'profile',
    'quote',
    'quote-short',
    'quotes',
    'search',
    'search-ticker',
    'income-statement',
    'balance-sheet-statement',
    'cash-flow-statement',
    'ratios',
    'enterprise-values',
    'key-metrics',
    'financial-growth',
    'rating',
    'discounted-cash-flow',
    'historical-discounted-cash-flow',
    'stock',
    'earning_calendar',
    'historical',
    'historical-chart',
    'stock-screener',
    'rss_feed',
    'sp500_constituent',
    'actives',
    'gainers',
    'losers',
    'market-hours',
    'sectors-performance'
]